name: Checker Diario Hola Car Rentals
on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  revisar_urls:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        batch: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install aiohttp beautifulsoup4  # <--- NUEVA LIBRERÍA INSTALADA
      - run: python checker_github.py ${{ matrix.batch }} 10
      - uses: actions/upload-artifact@v4
        with:
          name: reporte-${{ matrix.batch }}
          path: resultado_batch_${{ matrix.batch }}.csv

  unificar_y_enviar:
    needs: revisar_urls
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: resultados
          pattern: reporte-*
          merge-multiple: true
      
      - name: Unificar archivos
        run: |
          echo "URL,Status,Idioma,H1,H2,MetaTitle,MetaDescription" > reporte_final_total.csv
          tail -q -n +2 resultados/resultado_batch_*.csv >> reporte_final_total.csv
          
      - name: Enviar reporte a n8n
        run: |
          curl -X POST \
          -H "Content-Type: multipart/form-data" \
          -F "file=@reporte_final_total.csv" \
          https://holateam.app.n8n.cloud/webhook/phase1-intake
