name: Checker Diario Hola Car Rentals
on:
  schedule:
    - cron: '0 11 * * *' # Esto ejecuta el script a las 6:00 AM (Hora Colombia/CDMX)
  workflow_dispatch: # Esto permite que lo actives tú manualmente cuando quieras

jobs:
  revisar_urls:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # GitHub lanzará 10 servidores virtuales al mismo tiempo
        batch: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python en el servidor
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar librerías necesarias
        run: pip install aiohttp

      - name: Ejecutar revisión del bloque correspondiente
        run: python checker_github.py ${{ matrix.batch }} 10

      - name: Guardar el reporte generado por esta máquina
        uses: actions/upload-artifact@v4
        with:
          name: reporte-parcial-${{ matrix.batch }}
          path: resultado_batch_${{ matrix.batch }}.csv
          retention-days: 5 # Los archivos se borrarán solitos en 5 días para no ocupar espacio
